# Generated by Django 6.0 on 2026-02-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adzuna_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("company", models.CharField(blank=True, max_length=300)),
                ("location", models.CharField(blank=True, max_length=300)),
                (
                    "normalized_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("posted_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField()),
            ],
        ),
    ]
